/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssetMetadata {
  'id' : string,
  'name' : string,
  'size' : bigint,
  'projectId' : string,
  'blobId' : string,
  'assetType' : AssetType,
}
export type AssetType = { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface Project {
  'id' : string,
  'stateJson' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'assetIds' : Array<string>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAsset' : ActorMethod<[AssetMetadata], undefined>,
  'createAssets' : ActorMethod<[Array<AssetMetadata>], undefined>,
  'createProject' : ActorMethod<[string, string, string], undefined>,
  'deleteAsset' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAssetMetadata' : ActorMethod<[string], [] | [AssetMetadata]>,
  'getAssetsByProject' : ActorMethod<[string], Array<AssetMetadata>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getProjectsByOwner' : ActorMethod<[Principal], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProjects' : ActorMethod<[], Array<Project>>,
  'reindex' : ActorMethod<[], undefined>,
  'updateAsset' : ActorMethod<[AssetMetadata], undefined>,
  'updateProject' : ActorMethod<[string, Project], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];