/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const AssetMetadata = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'projectId' : IDL.Text,
  'blobId' : IDL.Text,
  'assetType' : AssetType,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Text,
  'stateJson' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'assetIds' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAsset' : IDL.Func([AssetMetadata], [], []),
  'createAssets' : IDL.Func([IDL.Vec(AssetMetadata)], [], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteAsset' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAssetMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AssetMetadata)],
      ['query'],
    ),
  'getAssetsByProject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssetMetadata)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjectsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'reindex' : IDL.Func([], [], []),
  'updateAsset' : IDL.Func([AssetMetadata], [], []),
  'updateProject' : IDL.Func([IDL.Text, Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const AssetMetadata = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'projectId' : IDL.Text,
    'blobId' : IDL.Text,
    'assetType' : AssetType,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Text,
    'stateJson' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'assetIds' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAsset' : IDL.Func([AssetMetadata], [], []),
    'createAssets' : IDL.Func([IDL.Vec(AssetMetadata)], [], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteAsset' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAssetMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AssetMetadata)],
        ['query'],
      ),
    'getAssetsByProject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssetMetadata)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjectsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'reindex' : IDL.Func([], [], []),
    'updateAsset' : IDL.Func([AssetMetadata], [], []),
    'updateProject' : IDL.Func([IDL.Text, Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };